# @package _global_

defaults:
  - /model: disc_mlp
  - /energy: ising
  - /optim: adam
  - _self_

train_fn:
  _target_: train.iefm_disc.train


num_steps: 1000

batch_size: 300
inner_iter: 100
iter: 100
num_sample_to_collect: 2000

num_mc_samples: 1000
loss_type: mse

prioritized_buffer: null

use_gt_sample: false


wandb:
  tags:
    - disc-iefm