seed: 12345
device: cuda

defaults:
  - _self_
  - algo: iefm_disc

hydra:
  run:
    dir: results/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep: 
    dir: results/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

wandb:
  use: true
  project: EGM
  tags:
    - disc-iefm