_target_: energy.rbm.GaussianBernoulliRBM

# RBM parameters
n_visible: 2
n_hidden: 3
sigma: 1.0
w_coeff: 0.01

# Sampling parameters
num_samples: 100000
num_chains: 100
burn_in: 10000
thinning: 100

device: "cuda"

param_file_name: "energy/rbm_params/rbm_nv2_nh3_sigma1_six_modes.pt"
